# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x1b\n\rUserIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\"<\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t2\x80\x01\n\x0bUserService\x12\x36\n\x0bGetUserById\x12\x13.user.UserIdRequest\x1a\x12.user.UserResponse\x12\x39\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERIDREQUEST']._serialized_start=20
  _globals['_USERIDREQUEST']._serialized_end=47
  _globals['_CREATEUSERREQUEST']._serialized_start=49
  _globals['_CREATEUSERREQUEST']._serialized_end=102
  _globals['_USERRESPONSE']._serialized_start=104
  _globals['_USERRESPONSE']._serialized_end=164
  _globals['_USERSERVICE']._serialized_start=167
  _globals['_USERSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
