version: "3.9"

services:
  auth:
    build: ./services/auth
    ports:
      - "8000:8000"
    env_file:
      - ./services/auth/.env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user:
    build: ./services/user
    env_file:
      - ./services/user/.env
    depends_on:
     - db_user

  db_user:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5433:5433"

volumes:
  pgdata:
